### ISSUE TITLE
Autocompletion box opens everytime

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [angular-ui/AngularJS-Atom#83]
On javascript file, after every character it appears suggestions from your plugin which is counter productive working like that. Even with a space triggers the box with all the suggestions

**Comment by outsideris** [comment]
I didn't realize that. I have an idea why that happened.I will check it.

**Comment by Autalyst** [comment]
I am getting this too, but mostly with commas. Every time I have a comma it tries to autocomplete and then I end up with a lot of garbage because I'm trying to put in a new line.

**Comment by FrEaKmAn** [comment]
Yes, same problem here. Super annoying

**Comment by Sparksx** [comment]
Same problem

**Comment by gmanriqueUy** [comment]
Same here!

**Comment by outsideris** [comment]
I just released [v0.5.2](https://github.com/angular-ui/AngularJS-Atom/releases/tag/v0.5.2). 
Please check it again.

**Comment by Sparksx** [comment]
Fixed for me in v0.5.2

Thanks @outsideris

**Comment by tiagomsmagalhaes** [comment]
@outsideris updated the plugin and still appears everytime

**Comment by Autalyst** [comment]
It appears to be resolved for me in v0.5.2

**Comment by outsideris** [comment]
@tiagomsmagalhaes Could you explain more details? Others said it is fixed. OS or Atom versions?

**Comment by tiagomsmagalhaes** [comment]
@outsideris comma doesn't trigger suggestions but spacebar does.

Windows 10
Atom 1.23.2 x64

**Package list from apm:**
angularjs@0.5.2
atom-clock@0.1.15
atom-live-server@2.2.0
atom-typescript@11.0.10
autocomplete-angular-material@0.4.0
busy-signal@1.4.3
editorconfig@2.2.2
emmet@2.4.3
file-icons@2.1.15
git-clone@0.2.0
git-plus@7.10.0
intentions@1.1.5
linter@2.2.0
linter-ui-default@1.6.10
multi-cursor@2.1.5
zip-folder@3.2.0

**Comment by outsideris** [comment]
@tiagomsmagalhaes I got it. Thank you.

**Comment by dierol** [comment]
Works fine in v0.5.2.
Thanks for this fix! It was an ungodly annoying behavior.

**Comment by tiagomsmagalhaes** [comment]
@outsideris  Updated to 0.5.3 Still happens...

Use cases:

- Entering space after a semicolon
- Opening parenthesis with cursor after parenthesis and before any word
- Entering space After the opening curly bracket (e.g. the bracket opening a function)
- Entering space after opening square brackets
- Entering dot everywhere (Not sure when is supposed to show if it's supposed to show)

**Comment by Sparksx** [comment]
You should hide it with "non word characters" (look at: atom > preference > editor)
by default it's set to: /\()"':,.;<>~!@#$%^&*|+=[]{}`?-…
suggestion have no sense after these characters, except after dot?

**Comment by tiagomsmagalhaes** [comment]
@Sparksx you replied to me or @outsideris?

Either way, I have that default non word characters with the default set. But that only works on html (angular) files. on js files the use cases i listed occurs.

**Comment by Sparksx** [comment]
I replied to @outsideris 

I've same problem that you @tiagomsmagalhaes

**Comment by outsideris** [comment]
hmm Now I just checking characters but I should determine with context.
I will dig it.
